### ISSUE TITLE
3.0.1 missing view 

### ISSUE THREAD

**Issue by herpaderpaldent** [dysath/seat-fitting#19]
![image](https://user-images.githubusercontent.com/6583519/42256321-e1b5df74-7f50-11e8-9b1d-3f2090b9da90.png)

seems the packagist ist not up2date. 

I tried to publish the assets, run migration and finally checked github. Realizing that there is no such view published. 
You may need to commit/push this view?

**Comment by dysath** [comment]
Fixed in 3.0.2
