### ISSUE TITLE
Fleet doctrine 

### ISSUE THREAD

**Issue by MagnusIIIBR** [dysath/seat-fitting#26]
In this screen i have in this doctrine 15 ships, but in the screen you can see he show only the first 8 ships of doctrine.

![image](https://user-images.githubusercontent.com/9530663/43687508-a95f02e8-98ac-11e8-8352-cfbc45a214e4.png)

---------------------------------------
In this screen i suggest change col-md-4 to col-md-12, because i have a lot of my screen without content.
![image](https://user-images.githubusercontent.com/9530663/43687574-9173c122-98ad-11e8-9207-655ef4c8d6b5.png)

![image](https://user-images.githubusercontent.com/9530663/43687576-92ef0f98-98ad-11e8-818a-e4b53f6037df.png)

![image](https://user-images.githubusercontent.com/9530663/43687577-9456ba20-98ad-11e8-87fd-a44f584b37df.png)

![image](https://user-images.githubusercontent.com/9530663/43687578-95966034-98ad-11e8-96f8-fb3217290efa.png)

![image](https://user-images.githubusercontent.com/9530663/43687580-979bc234-98ad-11e8-8014-e789eff8c304.png)
---------------------------------------

Anyway, I would like to congratulate you for the excellent add-on to the SEAT
👍

**Comment by dysath** [comment]
Thanks for the screenshots.  It shows me where I really need to beef up.  I'm in the middle of a permissions system with this module and having to sidetrack on a billing system.  Once I'm done with the IRS mod, I'll get back on fitting and fix the hell out of this stuff.

**Comment by Crypta-Eve** [comment]
Closed with #74
