### ISSUE TITLE
[FR]: Sorting corporation names in doctrine report 

### ISSUE THREAD

**Issue by kwazulueve** [dysath/seat-fitting#29]
See screenshot, I think you'll get what I mean :)

![image](https://user-images.githubusercontent.com/25641678/44992252-05618600-af97-11e8-9510-4dbd5d97c5c7.png)

Bonus points when the coporation of the superuser is automatically selected or at the top of the list 💃

**Comment by herpaderpaldent** [comment]
Hey @dysath could you take use of select2 and autocomplete when entering the corporation?
