### ISSUE TITLE
[Enhancements] Market total/ship/fit price

### ISSUE THREAD

**Issue by H4Z4RD-H42** [dysath/seat-fitting#30]
Would be fantastic if you can add a little Market section in fit views.

![image](https://user-images.githubusercontent.com/6650832/45375791-4d675500-b5f6-11e8-8d01-722ee35feab5.png)

**Comment by Crypta-Eve** [comment]
Added the total buy/sell cost for Jita in #77. There will be refinements and configuration in the future
