### ISSUE TITLE
Doctrine Report Limited

### ISSUE THREAD

**Issue by scopehs** [dysath/seat-fitting#31]
Doctrine Report is only showing stats for 8 fits per doctrine.

**Comment by rupertd** [comment]
I got nine showing out of a doctrine with eighteen total.

**Comment by tohuw** [comment]
This is happening to me also: I only see 8 fittings anytime I run a doctrine report. The ninth and onward are blank columns.

```
| Vendor   | Package Name           | Installed Version        |
| -------- | ---------------------- | ------------------------ |
| eveseat  | api                    | 4.1.0                    |
| eveseat  | console                | 4.0.5                    |
| eveseat  | eveapi                 | 4.2.0                    |
| eveseat  | notifications          | 4.0.3                    |
| eveseat  | services               | 4.0.0                    |
| eveseat  | web                    | 4.2.3                    |
| denngarr | seat-fitting           | 4.0.1                    |
| denngarr | seat-srp               | 4.0.5                    |
| warlof   | seat-connector         | 2.0.2                    |
| warlof   | seat-discord-connector | 5.0.0                    |
| ccp      | eve_online_sde         | sde-20201024-TRANQUILITY |
```

**Comment by baczoni** [comment]
+1, but only getting 4 columns to populate. Running latest on Docker

**Comment by Crypta-Eve** [comment]
So, this appears to occur when you have duplicate fit names in the doctrine. Can you guys confirm if this is the case @baczoni @tohuw @scopehs @rupertd

**Comment by Crypta-Eve** [comment]
I have added a warning regarding duplicate fit names, however in the interest of backward compat I will not enforce it at this time. If this issue persists for anyone outside of the duplicate names solution please reopen.
