### ISSUE TITLE
Feature on doctrine report

### ISSUE THREAD

**Issue by Alf-Life** [dysath/seat-fitting#36]
Hello,

is it possible to have a report for a complete alliance ?

thx

**Comment by odboEVEtech** [comment]
This woudld be wonderful! Seconded!

**Comment by entropylaw** [comment]
I third this request.

**Comment by MokeyII** [comment]
I too would love this. Right now, with 9 corps and 600+ people. Going to each corp and adding them all is time consuming considering the report runs after all queues are finished.

**Comment by Alf-Life** [comment]
yeahh it's ok !!!
