### ISSUE TITLE
Report show all corporations

### ISSUE THREAD

**Issue by Crazyht** [dysath/seat-fitting#48]
All corporation admin need request doctrine report for corresponding corpo, but for the moment if I add "Fitting.reportview"with only 1 affiliation, they can view report for all corporations.

How I can restrict report for only corporation in "Affiliation" (or other setting) ?

**Comment by Crypta-Eve** [comment]
As it is you cant and not something I will look at for now. The affiliation has no affect on permissions for the plugin. This is more clear in seat 4 with how limits are applied to permissions. 

I may look into this more in the future but for now not on my radar.
