### ISSUE TITLE
Trying to get property 'typeID' of non-object

### ISSUE THREAD

**Issue by mikalv** [dysath/seat-fitting#53]
![image](https://user-images.githubusercontent.com/195767/89803327-f5fbf780-db32-11ea-8220-5e9d8b3dd4d1.png)

Haven't been able to figure out exactly which fitting/ship it can't handle, but what about a "try-catch" for the array_push around line 195 in FittingsController.php ? :)

**Comment by Crypta-Eve** [comment]
Hi! Thanks for the input... I can't tell you which fitting to look for other than to say the culprit is the changed names as part of ccps ongoing tiericide.

SeAT 4 is just around the corner and I have code in place on my test bench which deals with this issue more elegantly...

**Comment by veteranmina** [comment]
I'll see if I can't come up with a sql statement that can catch the tiercide changes and post it here later. I remember writing one back for mine to mass change them.

**Comment by veteranmina** [comment]
If you are comfortable with SQL, you can run this as a SQL script. I ran this on my server successfully. 

WARNING: BACKUP YOUR DATABASE BEFORE THIS. I AM NOT RESPONSIBLE FOR ANY ISSUES THIS MIGHT CAUSE. 
[TierCide changes.zip](https://github.com/dysath/seat-fitting/files/5067494/TierCide.changes.zip)

**Comment by Crypta-Eve** [comment]
There is a command being added shortly which will deal with all invalid fits.

**Comment by Crypta-Eve** [comment]
Closing this as all future dev on it will be handled in the same manner as #49
