### ISSUE TITLE
Error when adding fitting

### ISSUE THREAD

**Issue by bradleyshelley** [dysath/seat-fitting#64]
ErrorException
Undefined offset: 1

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/denngarr/seat-fitting/src/Http/Controllers/FittingController.php:240

**Comment by Crypta-Eve** [comment]
Can you please provide the full stack trace. Preferably in a code block :)

**Comment by bradleyshelley** [comment]
![image](https://user-images.githubusercontent.com/66140401/91114296-325c4700-e64d-11ea-843d-377baad231ff.png)

**Comment by Crypta-Eve** [comment]
Can you post the fit here that you are tying to add?

**Comment by bradleyshelley** [comment]
[Heretic,Heretic Dictor I]
Small Ancillary Armor Repairer
Multispectrum Coating II
Multispectrum Energized Membrane II

5MN Quad LiF Restrained Microwarpdrive
Fleeting Compact Stasis Webifier
Warp Scrambler II

'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
Prototype Cloaking Device I
Interdiction Sphere Launcher I

Small Trimark Armor Pump II
Small Processor Overclocking Unit II


Caldari Navy Mjolnir Rocket x1270
Warp Disrupt Probe x26
Nanite Repair Paste x25
Caldari Navy Scourge Rocket x1000

**Comment by Crypta-Eve** [comment]
Your fit is invalid. You need a space after the comma in the name. As below
```
[Heretic, Heretic Dictor I]
Small Ancillary Armor Repairer
Multispectrum Coating II
Multispectrum Energized Membrane II

5MN Quad LiF Restrained Microwarpdrive
Fleeting Compact Stasis Webifier
Warp Scrambler II

'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
'Arbalest' Rocket Launcher I
Prototype Cloaking Device I
Interdiction Sphere Launcher I

Small Trimark Armor Pump II
Small Processor Overclocking Unit II

Caldari Navy Mjolnir Rocket x1270
Warp Disrupt Probe x26
Nanite Repair Paste x25
Caldari Navy Scourge Rocket x1000
```

**Comment by bradleyshelley** [comment]
Thank you!!!
