### ISSUE TITLE
Version shown as vv4.0.3

### ISSUE THREAD

**Issue by zmsMarc** [dysath/seat-fitting#67]
![ZNok7lj](https://user-images.githubusercontent.com/9104198/103105115-eab1f000-462b-11eb-90f8-ac88e3e124bc.png)

just updated to the newest version and its showing as outdated

**Comment by shinzoke** [comment]
Same problem over here... 
Just updated my SeAT install and got me the same error... 

It's showing a "wrong" kind of version... *Points towards VV4*

Greetz,
Shinni

**Comment by hibiki12y** [comment]
Same here
And I can't see fitting page : it return 500 http error

**Comment by Crypta-Eve** [comment]
Yeah, its just a cosmetic error really. Doesnt cause a functionality issue. Will be fixed in next update

@hibiki12y getting a 500 is nothing to do with this issue, please check you logs and either contact me in seat slack, or open another issue.

**Comment by Crypta-Eve** [comment]
As far as I am aware this is fixed. Feel free to reopen if required
