### ISSUE TITLE
Drones not shown in Fitting

### ISSUE THREAD

**Issue by veteranmina** [dysath/seat-fitting#68]
Looking through I found that if you copy/paste directly from in-game to SeAT there will be generally 2 extra lines between the rigs and drones.

If I delete the two extra lines SeAT-Fittings will then display the drones as intended. 

I am currently looking into a way to regex the extra lines out without causing needed blank lines from being removed.

**Comment by veteranmina** [comment]
Pull request #69 made to correct. :-)

**Comment by Crypta-Eve** [comment]
Ive merged, will tag a new release soon for you

**Comment by veteranmina** [comment]
Issue fixed per #69
