### ISSUE TITLE
HTML Syntax Issues in src/resources/views/fitting.blade.php

### ISSUE THREAD

**Issue by sportshead** [dysath/seat-fitting#72]
There are two HTML issues on the fitting page. 
https://github.com/dysath/seat-fitting/blob/dcb78f0327082f0d1cc0211e310010b381480d07/src/resources/views/fitting.blade.php#L37
This shouldn't be using `id`s, as they are repeated. They should be using `class` instead.

https://github.com/dysath/seat-fitting/blob/dcb78f0327082f0d1cc0211e310010b381480d07/src/resources/views/fitting.blade.php#L122
This is invalid HTML, I assume you meant `<input type="hidden" id="fittingId" value="" />`? Firefox attempts to "fix" it by rendering this:
![image](https://user-images.githubusercontent.com/32637656/112081201-3be76680-8bbe-11eb-8f6f-3b0360b46f04.png)

These should theoretically be quite easy to fix.

**Comment by warlof** [comment]
sounds like to be a good first issue, why not trying to send a pull request including the change? 😊
