### ISSUE TITLE
Missing Required Skills column on a particular user.

### ISSUE THREAD

**Issue by shinzoke** [dysath/seat-fitting#79]
For some sort of wichcraft i cant get my corp ceo to view he's required skills section when he's looking at a fit.
using the impersonate function i've been able to "recreate" that problem..
but it only occurs on that account.
when i'm impersonating some other account(s) not a single account is affected with that problem...
i've been checking the console using the chrome-dev-tools and stumbled upon a GET error with the fitting-link.

the only thing i can suggest for our CEO to do is to delete the toons and/or the account and re-register.
but befor i tell him to do that, i want to make sure that it's not because of some permissions setting etc...

Cheerz,
Shinzoke
![afbeelding_2021-04-22_191336](https://user-images.githubusercontent.com/54216870/115757897-d645f000-a39e-11eb-8c36-b70eea915273.png)

**Comment by veteranmina** [comment]
@shinzoke Is this still an issue, if so can you verify the scopes of the user and that skills are populated on the character(s) sheet?

**Comment by shinzoke** [comment]
Seems to be resolved now... 
and we are running the latest version.
if i/we encounter something in relation to this one, i'll open a new issue. this one can be closed :)
