### ISSUE TITLE
Internal API for other seat modules

### ISSUE THREAD

**Issue by recursivetree** [dysath/seat-fitting#85]
I'm writing an inventory management tool for my corp. As a feature, we would like to calculate stocks of our doctrines. These doctrines should be loaded from the fitting plugin. Should I just directly bind to the Fitting Model, or should I submit a pull request that adds a layer of abstraction with an api?

**Comment by alkari-verende** [comment]
I'm looking at doing something similar, and found possibly related work in the [whtools](https://github.com/flyingferret/seat-whtools) SeAT plugin. That plugin [directly references](https://github.com/alkari-verende/seat-whtools/blob/master/src/Models/Stocklvl.php#L18) the models from this fitting plugin.

**Comment by recursivetree** [comment]
I ended up doing that.
https://github.com/recursivetree/seat-inventory/blob/master/src/Helpers/FittingPluginHelper.php
https://github.com/recursivetree/seat-inventory/blob/master/src/Http/Controllers/InventoryController.php, line 233
