### ISSUE TITLE
Seat 5.0

### ISSUE THREAD

**Issue by martinskalicky** [dysath/seat-fitting#95]
Hello,

is there any chance this might be ported to Seat 5.0? We are heavily using this and would like to upgrade to Seat 5.0.

Martin

**Comment by JacobOkanta** [comment]
Is there any update on this? Looking forward to using with Seat v5

**Comment by Crypta-Eve** [comment]
Apologies I have not been keeping track of this older  repo. A fork was created and is available as `cryptatech/seat-fitting` where all future dev was completed. https://github.com/eveseat-plugins/seat-fitting
